{"timestamp":"2025-08-21T09:28:56.718510","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-21T09:28:56.719278","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/fetchin_cleaning.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-21T09:28:56.794400Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:56.794895Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:56.797267Z","level":"info","event":"Current task name:clean_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:56.797692Z","level":"info","event":"Dag name:weather_to_snowflake_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.278714Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.279259Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 175, in <module>","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.284604Z","level":"error","event":"    data_cleaning()","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.285113Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 153, in data_cleaning","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.287058Z","level":"error","event":"    pollutants_fact.to_csv(POLLUTANTS_FACT_FILE, index=False)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.287616Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py\", line 3902, in to_csv","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.289898Z","level":"error","event":"    return DataFrameRenderer(formatter).to_csv(","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.290431Z","level":"error","event":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.290781Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py\", line 1152, in to_csv","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.291170Z","level":"error","event":"    csv_formatter.save()","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.291484Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py\", line 247, in save","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.291860Z","level":"error","event":"    with get_handle(","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.292190Z","level":"error","event":"         ^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.292514Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py\", line 863, in get_handle","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.292872Z","level":"error","event":"    handle = open(","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.293149Z","level":"error","event":"             ^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.293431Z","level":"error","event":"PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/pollutants_fact.csv'","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.465653","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/fetchin_cleaning.py","lineno":16,"name":"clean_data"},{"filename":"/usr/local/lib/python3.12/subprocess.py","lineno":571,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-21T09:28:58.468175Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.468792Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.469173Z","level":"info","event":"Task:<Task(PythonOperator): clean_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:58.469640Z","level":"info","event":"Failure caused by Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","chan":"stdout","logger":"task"}
