{"timestamp":"2025-08-21T09:28:12.988366","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-21T09:28:12.989604","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/fetchin_cleaning.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-21T09:28:13.096243Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:13.097369Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:13.100881Z","level":"info","event":"Current task name:load_pollutants_fact","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:13.101371Z","level":"info","event":"Dag name:weather_to_snowflake_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:13.097409","level":"info","event":"Executing: \n        COPY INTO POLLUTION_OVERTIME.POLLUTANTS_FACT\n        FROM '@%POLLUTANTS_FACT'\n        FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='\"' SKIP_HEADER=1)\n        FORCE = TRUE;\n        ","logger":"airflow.task.operators.airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator"}
{"timestamp":"2025-08-21T09:28:13.100233","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-21T09:28:13.115812","level":"info","event":"Connection Retrieved 'weather_pollution'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-21T09:28:13.772352","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-21T09:28:13.788982","level":"info","event":"Connection Retrieved 'weather_pollution'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-21T09:28:13.789467","level":"info","event":"Snowflake Connector for Python Version: 3.16.0, Python Version: 3.12.11, Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.36","logger":"snowflake.connector.connection"}
{"timestamp":"2025-08-21T09:28:13.790204","level":"info","event":"Connecting to GLOBAL Snowflake domain","logger":"snowflake.connector.connection"}
{"timestamp":"2025-08-21T09:28:14.848554","level":"info","event":"Running statement: COPY INTO POLLUTION_OVERTIME.POLLUTANTS_FACT\n        FROM '@%POLLUTANTS_FACT'\n        FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='\"' SKIP_HEADER=1)\n        FORCE = TRUE;, parameters: None","logger":"airflow.task.hooks.airflow.providers.snowflake.hooks.snowflake.SnowflakeHook"}
{"timestamp":"2025-08-21T09:28:14.848755","level":"info","event":"Running statement: COPY INTO POLLUTION_OVERTIME.POLLUTANTS_FACT\n        FROM '@%POLLUTANTS_FACT'\n        FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='\"' SKIP_HEADER=1)\n        FORCE = TRUE;, parameters: None","logger":"airflow.task.hooks.airflow.providers.snowflake.hooks.snowflake.SnowflakeHook"}
{"timestamp":"2025-08-21T09:28:16.860507","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ProgrammingError","exc_value":"100080 (22000): 01be83d8-0000-abf4-0000-c31d000545d6: Number of columns in file (15) does not match that of the corresponding table (13), use file format option error_on_column_count_mismatch=false to ignore this error\n  File '@POLLUTANTS_FACT/pollutants_fact.csv.gz', line 3, character 1\n  Row 1 starts at line 2, column \"POLLUTANTS_FACT\"[15]\n  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py","lineno":312,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py","lineno":547,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":815,"name":"_run_command"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py","lineno":1137,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":279,"name":"errorhandler_wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":334,"name":"hand_to_other_handler"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":210,"name":"default_errorhandler"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-21T09:28:16.863462Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:16.863946Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:16.864275Z","level":"info","event":"Task:<Task(SQLExecuteQueryOperator): load_pollutants_fact>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:16.864600Z","level":"info","event":"Failure caused by 100080 (22000): 01be83d8-0000-abf4-0000-c31d000545d6: Number of columns in file (15) does not match that of the corresponding table (13), use file format option error_on_column_count_mismatch=false to ignore this error","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:16.864992Z","level":"info","event":"  File '@POLLUTANTS_FACT/pollutants_fact.csv.gz', line 3, character 1","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:16.865285Z","level":"info","event":"  Row 1 starts at line 2, column \"POLLUTANTS_FACT\"[15]","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T09:28:16.865579Z","level":"info","event":"  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.","chan":"stdout","logger":"task"}
